CREATE TABLE series (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    source_url VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE teams (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    short_name VARCHAR(32),
    image_url VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE players (
    id VARCHAR(64) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(64),
    image_url VARCHAR(1000),
    batting_style VARCHAR(128),
    bowling_style VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE matches (
    id VARCHAR(64) PRIMARY KEY,
    series_id VARCHAR(64),
    name VARCHAR(500) NOT NULL,
    match_type VARCHAR(64),
    category VARCHAR(32) NOT NULL,
    status VARCHAR(1000),
    venue VARCHAR(500),
    start_time TIMESTAMP WITH TIME ZONE,
    detail_link VARCHAR(1000),
    source_payload TEXT,
    last_synced_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_matches_series FOREIGN KEY (series_id) REFERENCES series(id)
);

CREATE INDEX idx_matches_category_start ON matches(category, start_time);
CREATE INDEX idx_matches_series ON matches(series_id);

CREATE TABLE match_teams (
    match_id VARCHAR(64) NOT NULL,
    team_id VARCHAR(64) NOT NULL,
    team_order INTEGER NOT NULL,
    score VARCHAR(128),
    PRIMARY KEY (match_id, team_id),
    CONSTRAINT fk_match_teams_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_match_teams_team FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE innings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id VARCHAR(64) NOT NULL,
    team_id VARCHAR(64),
    inning_number INTEGER NOT NULL,
    runs INTEGER NOT NULL DEFAULT 0,
    wickets INTEGER NOT NULL DEFAULT 0,
    overs DECIMAL(8,2) NOT NULL DEFAULT 0,
    extras INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_innings_match_number UNIQUE (match_id, inning_number),
    CONSTRAINT fk_innings_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_innings_team FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE batting_scorecards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inning_id BIGINT NOT NULL,
    player_id VARCHAR(64),
    batting_order INTEGER NOT NULL,
    runs INTEGER NOT NULL DEFAULT 0,
    balls INTEGER NOT NULL DEFAULT 0,
    fours INTEGER NOT NULL DEFAULT 0,
    sixes INTEGER NOT NULL DEFAULT 0,
    strike_rate DECIMAL(10,2) NOT NULL DEFAULT 0,
    dismissal_text VARCHAR(1000),
    CONSTRAINT fk_batting_inning FOREIGN KEY (inning_id) REFERENCES innings(id),
    CONSTRAINT fk_batting_player FOREIGN KEY (player_id) REFERENCES players(id)
);

CREATE TABLE bowling_scorecards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inning_id BIGINT NOT NULL,
    player_id VARCHAR(64),
    bowling_order INTEGER NOT NULL,
    overs DECIMAL(8,2) NOT NULL DEFAULT 0,
    maidens INTEGER NOT NULL DEFAULT 0,
    runs INTEGER NOT NULL DEFAULT 0,
    wickets INTEGER NOT NULL DEFAULT 0,
    economy DECIMAL(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_bowling_inning FOREIGN KEY (inning_id) REFERENCES innings(id),
    CONSTRAINT fk_bowling_player FOREIGN KEY (player_id) REFERENCES players(id)
);

CREATE TABLE scraping_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(64) NOT NULL,
    category VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    records_count INTEGER NOT NULL DEFAULT 0,
    error_message VARCHAR(2000),
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE
);
